name: poster-metadata-quality-code
channels:
  - defaults
  - conda-forge
dependencies:
  - python = 3.12.0
  - ipykernel = 6.29.5
  - openpyxl = 3.1.5
  - requests = 2.32.3
  - googlesearch = 3.0.0
  - ipywidgets
  - pip
  - pip:
      - pandas == 2.2.3
      - matplotlib == 3.10.0
      - seaborn == 0.13.2
